#!/usr/bin/env python3
from os import path
import sys


# always import from repository if running the command from here
sys.path.insert(0, path.abspath(path.join(path.dirname(__file__), path.pardir)))
from cashaccount import cli


cli.run(obj={})
